version : '3'
services:
  php:
    container_name: app_php
    build:
      context: .docker/php
      args:
        - WITH_XDEBUG=false
    env_file:
      - .env
    restart: always
    volumes:
      - ${SYMFONY_APP}:/var/www
      - .docker/php/php.ini:/usr/local/etc/php/php.ini
      - "$HOME/.composer/:/home/.composer/"
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: app_mysql
    restart: always
    volumes:
      - .docker/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  httpd:
    image: httpd:2.4
    container_name: app_httpd
    restart: always
    ports:
      - 81:80
    volumes:
      - ${SYMFONY_APP}:/var/www
      - .docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    links:
      - mysql
    depends_on:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app_phpmyadmin
    restart: always
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql

volumes:
  esvirtual:
    driver: local
